# config.yml

api:
  port: 8000
  host: localhost

proxy:
  port: 8080
  host: localhost

db:
  user: postgres
  port: 5432
  db_name: ProxyStorage
  app_name: ProxyStorage
  schema: public
  connection_timeout: 5

logging:
  # Accepted levels: trace, debug, info, warning, error
  level: debug
  disable_timestamp: false
  full_timestamp: true
  # If true, report_caller setting will be based on level being trace
  # If false, report_caller setting will use the config value
  level_based_report: true
  report_caller: true
  disable_level_truncation: true

tls:
  dir: ".tls"
  cert_dir: "certs"
  age_years: 10
  ca_key: "ca.key"
  ca_gen: "gen_ca.sh"
  ca_cert: "ca.crt"
  cert_key: "cert.key"
  cert_gen: "gen_cert.sh"
