name: Pull Request CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  composite-ci:
    name: Lint, build, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false
      
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest