name: Pull Request CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  composite-ci:
    name: Lint, build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false
      
      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest

      - name: Build .env file
        uses: ./.github/actions/build-dot-env
        with:
          migrator_pw: ${{ secrets.MIGRATOR_PASSWORD }}
          postgres_user: ${{ secrets.POSTGRES_USER }}
          postgres_pwd: ${{ secrets.POSTGRES_PASSWORD }}
          postgres_table: ${{ secrets.POSTGRES_TABLE }}
          postgres_host: ${{ secrets.POSTGRES_HOST }}
  
      - name: Build the api binary
        run: go build -o api ./cmd/api/api.go

      - name: Build the proxy binary
        run: go build -o proxy ./cmd/proxy/proxy.go
